<< CAP LS
<< NICK vladplk
<< USER vpolojie vpolojie irc.libera.chat :Vladimir Polojienko
>> :tantalum.libera.chat NOTICE * :*** Checking Ident
>> :tantalum.libera.chat NOTICE * :*** Looking up your hostname...
>> :tantalum.libera.chat NOTICE * :*** Couldn't look up your hostname
>> :tantalum.libera.chat NOTICE * :*** No Ident response
>> :tantalum.libera.chat CAP * LS :account-notify away-notify chghost extended-join multi-prefix sasl tls account-tag cap-notify echo-message server-time solanum.chat/identify-msg solanum.chat/oper solanum.chat/realhost
<< CAP REQ :multi-prefix
>> :tantalum.libera.chat 433 * vladplk :Nickname is already in use.
<< NICK vladplk_
>> :tantalum.libera.chat CAP * ACK :multi-prefix
<< CAP END
>> :tantalum.libera.chat 001 vladplk_ :Welcome to the Libera.Chat Internet Relay Chat Network vladplk_
<< MODE vladplk_ +i
<< WHOIS vladplk
>> :tantalum.libera.chat 002 vladplk_ :Your host is tantalum.libera.chat[93.158.237.2/6697], running version solanum-1.0-dev
>> :tantalum.libera.chat 003 vladplk_ :This server was created Sat Nov 18 2023 at 03:37:54 UTC
>> :tantalum.libera.chat 004 vladplk_ tantalum.libera.chat solanum-1.0-dev DGIMQRSZaghilopsuwz CFILMPQRSTbcefgijklmnopqrstuvz bkloveqjfI
>> :tantalum.libera.chat 005 vladplk_ ACCOUNTEXTBAN=a WHOX MONITOR=100 SAFELIST ELIST=CMNTU ETRACE FNC CALLERID=g KNOCK CHANTYPES=# EXCEPTS INVEX :are supported by this server
>> :tantalum.libera.chat 005 vladplk_ CHANMODES=eIbq,k,flj,CFLMPQRSTcgimnprstuz CHANLIMIT=#:250 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=Libera.Chat STATUSMSG=@+ CASEMAPPING=rfc1459 NICKLEN=16 MAXNICKLEN=16 CHANNELLEN=50 TOPICLEN=390 :are supported by this server
>> :tantalum.libera.chat 005 vladplk_ DEAF=D TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,agjrxz :are supported by this server
>> :tantalum.libera.chat 251 vladplk_ :There are 69 users and 35658 invisible on 28 servers
>> :tantalum.libera.chat 252 vladplk_ 44 :IRC Operators online
>> :tantalum.libera.chat 253 vladplk_ 79 :unknown connection(s)
>> :tantalum.libera.chat 254 vladplk_ 23325 :channels formed
>> :tantalum.libera.chat 255 vladplk_ :I have 2387 clients and 1 servers
>> :tantalum.libera.chat 265 vladplk_ 2387 2963 :Current local users 2387, max 2963
>> :tantalum.libera.chat 266 vladplk_ 35727 37286 :Current global users 35727, max 37286
>> :tantalum.libera.chat 250 vladplk_ :Highest connection count: 2964 (2963 clients) (709473 connections received)
>> :tantalum.libera.chat 375 vladplk_ :- tantalum.libera.chat Message of the Day - 
>> :tantalum.libera.chat 372 vladplk_ :- This server provided by Hyperfilter (https://hyperfilter.com)
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :- Welcome to Libera Chat, the IRC network for
>> :tantalum.libera.chat 372 vladplk_ :- free & open-source software and peer directed projects.
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :- Use of Libera Chat is governed by our network policies.
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :- To reduce network abuses we perform open proxy checks
>> :tantalum.libera.chat 372 vladplk_ :- on hosts at connection time.
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :- Please visit us in #libera for questions and support.
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :- Website and documentation:  https://libera.chat
>> :tantalum.libera.chat 372 vladplk_ :- Webchat:                    https://web.libera.chat
>> :tantalum.libera.chat 372 vladplk_ :- Network policies:           https://libera.chat/policies
>> :tantalum.libera.chat 372 vladplk_ :- Email:                      support@libera.chat
>> :tantalum.libera.chat 376 vladplk_ :End of /MOTD command.
>> :vladplk_ MODE vladplk_ :+Ziw
<< PING tantalum.libera.chat
>> :tantalum.libera.chat 311 vladplk_ vladplk ~vpolojie 62.129.8.171 * :Vladimir Polojienko
--> nickfind event whois
>> :tantalum.libera.chat 312 vladplk_ vladplk tantalum.libera.chat :Amsterdam, NL
--> event empty
>> :tantalum.libera.chat 671 vladplk_ vladplk :is using a secure connection
--> event empty
>> :tantalum.libera.chat 338 vladplk_ vladplk 62.129.8.171 :actually using host
--> event empty
>> :tantalum.libera.chat 317 vladplk_ vladplk 12 1717665212 :seconds idle, signon time
--> event empty
>> :tantalum.libera.chat 318 vladplk_ vladplk :End of /WHOIS list.
--> event empty
>> :tantalum.libera.chat PONG tantalum.libera.chat :tantalum.libera.chat
--> lag pong
<< JOIN #vladplk
>> :vladplk_!~vpolojie@62.129.8.171 JOIN #vladplk
>> :tantalum.libera.chat 353 vladplk_ @ #vladplk :vladplk_ @vladplk
>> :tantalum.libera.chat 366 vladplk_ #vladplk :End of /NAMES list.
<< MODE #vladplk
>> :tantalum.libera.chat 324 vladplk_ #vladplk +Cnst
--> chanquery mode
<< WHO #vladplk
>> :tantalum.libera.chat 329 vladplk_ #vladplk 1717665226
--> event 329
>> :tantalum.libera.chat 352 vladplk_ #vladplk ~vpolojie 62.129.8.171 tantalum.libera.chat vladplk_ H :0 Vladimir Polojienko
--> silent event who
>> :tantalum.libera.chat 352 vladplk_ #vladplk ~vpolojie 62.129.8.171 tantalum.libera.chat vladplk H@ :0 Vladimir Polojienko
--> silent event who
>> :tantalum.libera.chat 315 vladplk_ #vladplk :End of /WHO list.
--> chanquery who end
<< MODE #vladplk b
>> :tantalum.libera.chat 368 vladplk_ #vladplk :End of Channel Ban List
--> chanquery ban end
>> :vladplk!~vpolojie@62.129.8.171 PRIVMSG #vladplk :bonjour
<< QUIT :leaving
<< CAP LS
<< NICK vladplk
<< USER vpolojie vpolojie irc.libera.chat :Vladimir Polojienko
>> :tantalum.libera.chat NOTICE * :*** Checking Ident
>> :tantalum.libera.chat NOTICE * :*** Looking up your hostname...
>> :tantalum.libera.chat NOTICE * :*** Couldn't look up your hostname
>> :tantalum.libera.chat NOTICE * :*** No Ident response
>> :tantalum.libera.chat CAP * LS :account-notify away-notify chghost extended-join multi-prefix sasl tls account-tag cap-notify echo-message server-time solanum.chat/identify-msg solanum.chat/oper solanum.chat/realhost
<< CAP REQ :multi-prefix
>> :tantalum.libera.chat 433 * vladplk :Nickname is already in use.
<< NICK vladplk_
>> :tantalum.libera.chat CAP * ACK :multi-prefix
<< CAP END
>> :tantalum.libera.chat 001 vladplk_ :Welcome to the Libera.Chat Internet Relay Chat Network vladplk_
<< MODE vladplk_ +i
<< WHOIS vladplk
>> :tantalum.libera.chat 002 vladplk_ :Your host is tantalum.libera.chat[93.158.237.2/6697], running version solanum-1.0-dev
>> :tantalum.libera.chat 003 vladplk_ :This server was created Sat Nov 18 2023 at 03:37:54 UTC
>> :tantalum.libera.chat 004 vladplk_ tantalum.libera.chat solanum-1.0-dev DGIMQRSZaghilopsuwz CFILMPQRSTbcefgijklmnopqrstuvz bkloveqjfI
>> :tantalum.libera.chat 005 vladplk_ ACCOUNTEXTBAN=a WHOX MONITOR=100 SAFELIST ELIST=CMNTU ETRACE FNC CALLERID=g KNOCK CHANTYPES=# EXCEPTS INVEX :are supported by this server
>> :tantalum.libera.chat 005 vladplk_ CHANMODES=eIbq,k,flj,CFLMPQRSTcgimnprstuz CHANLIMIT=#:250 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=Libera.Chat STATUSMSG=@+ CASEMAPPING=rfc1459 NICKLEN=16 MAXNICKLEN=16 CHANNELLEN=50 TOPICLEN=390 :are supported by this server
>> :tantalum.libera.chat 005 vladplk_ DEAF=D TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,agjrxz :are supported by this server
>> :tantalum.libera.chat 251 vladplk_ :There are 69 users and 35662 invisible on 28 servers
>> :tantalum.libera.chat 252 vladplk_ 44 :IRC Operators online
>> :tantalum.libera.chat 253 vladplk_ 108 :unknown connection(s)
>> :tantalum.libera.chat 254 vladplk_ 23325 :channels formed
>> :tantalum.libera.chat 255 vladplk_ :I have 2394 clients and 1 servers
>> :tantalum.libera.chat 265 vladplk_ 2394 2963 :Current local users 2394, max 2963
>> :tantalum.libera.chat 266 vladplk_ 35731 37286 :Current global users 35731, max 37286
>> :tantalum.libera.chat 250 vladplk_ :Highest connection count: 2964 (2963 clients) (709492 connections received)
>> :tantalum.libera.chat 375 vladplk_ :- tantalum.libera.chat Message of the Day - 
>> :tantalum.libera.chat 372 vladplk_ :- This server provided by Hyperfilter (https://hyperfilter.com)
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :- Welcome to Libera Chat, the IRC network for
>> :tantalum.libera.chat 372 vladplk_ :- free & open-source software and peer directed projects.
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :- Use of Libera Chat is governed by our network policies.
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :- To reduce network abuses we perform open proxy checks
>> :tantalum.libera.chat 372 vladplk_ :- on hosts at connection time.
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :- Please visit us in #libera for questions and support.
>> :tantalum.libera.chat 372 vladplk_ :-  
>> :tantalum.libera.chat 372 vladplk_ :- Website and documentation:  https://libera.chat
>> :tantalum.libera.chat 372 vladplk_ :- Webchat:                    https://web.libera.chat
>> :tantalum.libera.chat 372 vladplk_ :- Network policies:           https://libera.chat/policies
>> :tantalum.libera.chat 372 vladplk_ :- Email:                      support@libera.chat
>> :tantalum.libera.chat 376 vladplk_ :End of /MOTD command.
>> :vladplk_ MODE vladplk_ :+Ziw
<< JOIN #leonpolo
>> :tantalum.libera.chat 311 vladplk_ vladplk ~vpolojie 62.129.8.171 * :Vladimir Polojienko
--> nickfind event whois
>> :tantalum.libera.chat 312 vladplk_ vladplk mercury.libera.chat :London, UK
--> event empty
>> :tantalum.libera.chat 671 vladplk_ vladplk :is using a secure connection
--> event empty
>> :tantalum.libera.chat 338 vladplk_ vladplk 62.129.8.171 :actually using host
--> event empty
>> :tantalum.libera.chat 318 vladplk_ vladplk :End of /WHOIS list.
--> event empty
>> :vladplk_!~vpolojie@62.129.8.171 JOIN #leonpolo
>> :tantalum.libera.chat 353 vladplk_ @ #leonpolo :vladplk_ @vladplk
>> :tantalum.libera.chat 366 vladplk_ #leonpolo :End of /NAMES list.
<< MODE #leonpolo
>> :tantalum.libera.chat 324 vladplk_ #leonpolo +Cnst
--> chanquery mode
<< WHO #leonpolo
>> :tantalum.libera.chat 329 vladplk_ #leonpolo 1717665344
--> event 329
>> :tantalum.libera.chat 352 vladplk_ #leonpolo ~vpolojie 62.129.8.171 tantalum.libera.chat vladplk_ H :0 Vladimir Polojienko
--> silent event who
>> :tantalum.libera.chat 352 vladplk_ #leonpolo ~vpolojie 62.129.8.171 mercury.libera.chat vladplk H@ :0 Vladimir Polojienko
--> silent event who
>> :tantalum.libera.chat 315 vladplk_ #leonpolo :End of /WHO list.
--> chanquery who end
<< MODE #leonpolo b
>> :tantalum.libera.chat 368 vladplk_ #leonpolo :End of Channel Ban List
--> chanquery ban end
<< PING tantalum.libera.chat
>> :tantalum.libera.chat PONG tantalum.libera.chat :tantalum.libera.chat
--> lag pong
>> :vladplk!~vpolojie@62.129.8.171 PRIVMSG #leonpolo :bonjour
<< PRIVMSG #leonpolo :bonsoir
<< PRIVMSG #leonpolo :merci du message
>> :vladplk!~vpolojie@62.129.8.171 PRIVMSG #leonpolo :de rien
>> :vladplk!~vpolojie@62.129.8.171 PART #leonpolo
<< PART #leonpolo
>> :vladplk_!~vpolojie@62.129.8.171 PART #leonpolo
<< QUIT :leaving
